# This is a basic workflow to help you get started with Actions

name: back

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # 可以设定定时任务执行
  schedule:
    # UTC 0 点 30 定期执行一次，跟北京时间大概相距8小时，但因为排队可能会稍微延后半小时左右
    # 即北京时间 8 点 30 以后
    - cron: '30 09 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan_back:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # 配置安装 python 环境
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      # 配置安装依赖包
      - run: pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Scan
        run: python 369bus.py 378 花园路华信路 唐冶西路文苑街 306 花园路华信路 世纪大道龙凤山路 "17:30" "20:30"

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
